// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResListInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from ResListInfo.proto</summary>
public static partial class ResListInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for ResListInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ResListInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFSZXNMaXN0SW5mby5wcm90byI4CgtSZXNMaXN0SW5mbxILCgNWZXIYASAB",
          "KAkSHAoEaW5mbxgCIAMoCzIOLlNpbmdsZVJlc0luZm8iSAoNU2luZ2xlUmVz",
          "SW5mbxIMCgRQYXRoGAEgASgJEgsKA01kNRgCIAEoCRIMCgRTaXplGAMgASgF",
          "Eg4KBlN0YXR1cxgEIAEoBUICSANiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ResListInfo), global::ResListInfo.Parser, new[]{ "Ver", "Info" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::SingleResInfo), global::SingleResInfo.Parser, new[]{ "Path", "Md5", "Size", "Status" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class ResListInfo : pb::IMessage<ResListInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ResListInfo> _parser = new pb::MessageParser<ResListInfo>(() => new ResListInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<ResListInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResListInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ResListInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ResListInfo(ResListInfo other) : this() {
    ver_ = other.ver_;
    info_ = other.info_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ResListInfo Clone() {
    return new ResListInfo(this);
  }

  /// <summary>Field number for the "Ver" field.</summary>
  public const int VerFieldNumber = 1;
  private string ver_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Ver {
    get { return ver_; }
    set {
      ver_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "info" field.</summary>
  public const int InfoFieldNumber = 2;
  private static readonly pb::FieldCodec<global::SingleResInfo> _repeated_info_codec
      = pb::FieldCodec.ForMessage(18, global::SingleResInfo.Parser);
  private readonly pbc::RepeatedField<global::SingleResInfo> info_ = new pbc::RepeatedField<global::SingleResInfo>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::SingleResInfo> Info {
    get { return info_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as ResListInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(ResListInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ver != other.Ver) return false;
    if(!info_.Equals(other.info_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Ver.Length != 0) hash ^= Ver.GetHashCode();
    hash ^= info_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Ver.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Ver);
    }
    info_.WriteTo(output, _repeated_info_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Ver.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Ver);
    }
    info_.WriteTo(ref output, _repeated_info_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Ver.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Ver);
    }
    size += info_.CalculateSize(_repeated_info_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(ResListInfo other) {
    if (other == null) {
      return;
    }
    if (other.Ver.Length != 0) {
      Ver = other.Ver;
    }
    info_.Add(other.info_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Ver = input.ReadString();
          break;
        }
        case 18: {
          info_.AddEntriesFrom(input, _repeated_info_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Ver = input.ReadString();
          break;
        }
        case 18: {
          info_.AddEntriesFrom(ref input, _repeated_info_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class SingleResInfo : pb::IMessage<SingleResInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SingleResInfo> _parser = new pb::MessageParser<SingleResInfo>(() => new SingleResInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SingleResInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ResListInfoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SingleResInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SingleResInfo(SingleResInfo other) : this() {
    path_ = other.path_;
    md5_ = other.md5_;
    size_ = other.size_;
    status_ = other.status_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SingleResInfo Clone() {
    return new SingleResInfo(this);
  }

  /// <summary>Field number for the "Path" field.</summary>
  public const int PathFieldNumber = 1;
  private string path_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Path {
    get { return path_; }
    set {
      path_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Md5" field.</summary>
  public const int Md5FieldNumber = 2;
  private string md5_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Md5 {
    get { return md5_; }
    set {
      md5_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Size" field.</summary>
  public const int SizeFieldNumber = 3;
  private int size_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Size {
    get { return size_; }
    set {
      size_ = value;
    }
  }

  /// <summary>Field number for the "Status" field.</summary>
  public const int StatusFieldNumber = 4;
  private int status_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Status {
    get { return status_; }
    set {
      status_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SingleResInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SingleResInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Path != other.Path) return false;
    if (Md5 != other.Md5) return false;
    if (Size != other.Size) return false;
    if (Status != other.Status) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Path.Length != 0) hash ^= Path.GetHashCode();
    if (Md5.Length != 0) hash ^= Md5.GetHashCode();
    if (Size != 0) hash ^= Size.GetHashCode();
    if (Status != 0) hash ^= Status.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Path.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Path);
    }
    if (Md5.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Md5);
    }
    if (Size != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Size);
    }
    if (Status != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Status);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Path.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(Path);
    }
    if (Md5.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Md5);
    }
    if (Size != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Size);
    }
    if (Status != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Status);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Path.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Path);
    }
    if (Md5.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Md5);
    }
    if (Size != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Size);
    }
    if (Status != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Status);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SingleResInfo other) {
    if (other == null) {
      return;
    }
    if (other.Path.Length != 0) {
      Path = other.Path;
    }
    if (other.Md5.Length != 0) {
      Md5 = other.Md5;
    }
    if (other.Size != 0) {
      Size = other.Size;
    }
    if (other.Status != 0) {
      Status = other.Status;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          Path = input.ReadString();
          break;
        }
        case 18: {
          Md5 = input.ReadString();
          break;
        }
        case 24: {
          Size = input.ReadInt32();
          break;
        }
        case 32: {
          Status = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          Path = input.ReadString();
          break;
        }
        case 18: {
          Md5 = input.ReadString();
          break;
        }
        case 24: {
          Size = input.ReadInt32();
          break;
        }
        case 32: {
          Status = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
